export const SITE = {
  storeName: '三隻羊商行',
  taxID: '95212291',
  address: '970 花蓮縣花蓮市府前路396號',
  phone: '0982-724358',
  businessHours: '11:00-14:00 | 16:30-20:00 (週日公休)',
  bankName: '第一銀行(007)',
  bankAccount: '21668145798',
  bankAccountName: '盧玟攸',
  lineIcon: '/icon/line.svg',
  lineQrCode: '/qrcode/line.png',
  lineHref: 'https://lin.ee/ZfVn3c0',
  instagramIcon: '/icon/instagram.svg',
  instagramQrCode: '/qrcode/instagram.png',
  instagramHref: 'https://www.instagram.com/mutton_lu?igsh=azQ5b2lrZzhrZ2J4&utm_source=qr',
  metaIcon: '/icon/meta.svg',
  metaQrCode: '/qrcode/meta.png',
  metaHref: 'https://www.facebook.com/share/1BgyWtawdx/?mibextid=wwXIfr',
  GoogleMapQrCode: '/qrcode/googleMap.png',
  GoogleMapHref: 'https://maps.app.goo.gl/kXfNMhsPMo2FxvKS7',
}